---
# tasks file for openjdk
- name: Updating apt-get cache
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: install required packages
  apt:
    name: "{{ packages }}"
    state: present
  become: yes
  become_method: sudo

- name: Updating apt-get cache again
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: Transfer the script
  copy: src=export_variables.sh dest=$HOME/ mode=0777

- name: Execute the script
  shell: bash $HOME/export_variables.sh 
